### ISSUE TITLE
HashJoin executor: left_batchs is empty then return

### ISSUE THREAD

**Issue by KKould** [Fedomn/sql-query-engine-rs#153]
https://github.com/Fedomn/sqlrs/blob/main/src/executor/join/hash_join.rs#L183C9-L183C35

Maybe when the join type is Right or Full, the result is empty due to early exit

**Comment by Fedomn** [comment]
yep, instead of returning empty we should construct an empty `left_single_batch`. However, there had a tech debt to obtain the left child schema for constructing an empty batch. The refactor might be easier in planner v2. If you're interested, you could give it a try.
